@startuml FirstPersonPlayerLocomotionLogic
state "FirstPersonPlayerLocomotionLogic State" as GameDemo_FirstPersonPlayerLocomotionLogic_State {
  state "Active" as GameDemo_FirstPersonPlayerLocomotionLogic_State_Active {
    state "Airborne" as GameDemo_FirstPersonPlayerLocomotionLogic_State_Airborne {
      state "Falling" as GameDemo_FirstPersonPlayerLocomotionLogic_State_Falling
      state "Jumping" as GameDemo_FirstPersonPlayerLocomotionLogic_State_Jumping
      state "Liftoff" as GameDemo_FirstPersonPlayerLocomotionLogic_State_Liftoff
    }
    state "Grounded" as GameDemo_FirstPersonPlayerLocomotionLogic_State_Grounded {
      state "Crouching" as GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching {
        state "CrouchingIdle" as GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching_CrouchingIdle
        state "CrouchingMoving" as GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching_CrouchingMoving
      }
      state "Dashing" as GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing
      state "Idle" as GameDemo_FirstPersonPlayerLocomotionLogic_State_Idle
      state "Moving" as GameDemo_FirstPersonPlayerLocomotionLogic_State_Moving {
        state "Sprinting" as GameDemo_FirstPersonPlayerLocomotionLogic_State_Sprinting
      }
    }
  }
  state "Dead" as GameDemo_FirstPersonPlayerLocomotionLogic_State_Dead
}

GameDemo_FirstPersonPlayerLocomotionLogic_State_Active --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Active : CrouchEdgeBlockedChanged
GameDemo_FirstPersonPlayerLocomotionLogic_State_Active --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Active : CrouchEnded
GameDemo_FirstPersonPlayerLocomotionLogic_State_Active --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Active : CrouchStarted
GameDemo_FirstPersonPlayerLocomotionLogic_State_Active --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Active : DashRequested
GameDemo_FirstPersonPlayerLocomotionLogic_State_Active --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Active : Moved
GameDemo_FirstPersonPlayerLocomotionLogic_State_Active --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Active : PhysicsTick
GameDemo_FirstPersonPlayerLocomotionLogic_State_Active --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Active : Pushed
GameDemo_FirstPersonPlayerLocomotionLogic_State_Active --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Active : SprintEnded
GameDemo_FirstPersonPlayerLocomotionLogic_State_Active --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Active : SprintStarted
GameDemo_FirstPersonPlayerLocomotionLogic_State_Active --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Dead : Killed
GameDemo_FirstPersonPlayerLocomotionLogic_State_Airborne --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Airborne : DashRequested
GameDemo_FirstPersonPlayerLocomotionLogic_State_Airborne --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing : DashRequested
GameDemo_FirstPersonPlayerLocomotionLogic_State_Airborne --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Falling : StartedFalling
GameDemo_FirstPersonPlayerLocomotionLogic_State_Airborne --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Idle : HitFloor
GameDemo_FirstPersonPlayerLocomotionLogic_State_Airborne --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Moving : HitFloor
GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching : DashRequested
GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing : DashRequested
GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Idle : CrouchEnded
GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Moving : CrouchEnded
GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Sprinting : CrouchEnded
GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching_CrouchingIdle --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching_CrouchingMoving : StartedMovingHorizontally
GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching_CrouchingMoving --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching_CrouchingIdle : StoppedMovingHorizontally
GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing : CrouchEnded
GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing : CrouchStarted
GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing : DashRequested
GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing : PhysicsTick
GameDemo_FirstPersonPlayerLocomotionLogic_State_Grounded --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Falling : LeftFloor
GameDemo_FirstPersonPlayerLocomotionLogic_State_Grounded --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Jumping : Jump
GameDemo_FirstPersonPlayerLocomotionLogic_State_Grounded --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Liftoff : LeftFloor
GameDemo_FirstPersonPlayerLocomotionLogic_State_Idle --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching_CrouchingIdle : CrouchStarted
GameDemo_FirstPersonPlayerLocomotionLogic_State_Idle --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing : DashRequested
GameDemo_FirstPersonPlayerLocomotionLogic_State_Idle --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Idle : DashRequested
GameDemo_FirstPersonPlayerLocomotionLogic_State_Idle --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Moving : StartedMovingHorizontally
GameDemo_FirstPersonPlayerLocomotionLogic_State_Idle --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Sprinting : StartedMovingHorizontally
GameDemo_FirstPersonPlayerLocomotionLogic_State_Jumping --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Jumping : Jump
GameDemo_FirstPersonPlayerLocomotionLogic_State_Moving --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching_CrouchingMoving : CrouchStarted
GameDemo_FirstPersonPlayerLocomotionLogic_State_Moving --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing : DashRequested
GameDemo_FirstPersonPlayerLocomotionLogic_State_Moving --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Idle : StoppedMovingHorizontally
GameDemo_FirstPersonPlayerLocomotionLogic_State_Moving --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Moving : DashRequested
GameDemo_FirstPersonPlayerLocomotionLogic_State_Moving --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Sprinting : SprintStarted
GameDemo_FirstPersonPlayerLocomotionLogic_State_Sprinting --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching_CrouchingMoving : CrouchStarted
GameDemo_FirstPersonPlayerLocomotionLogic_State_Sprinting --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing : DashRequested
GameDemo_FirstPersonPlayerLocomotionLogic_State_Sprinting --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Idle : SprintEnded
GameDemo_FirstPersonPlayerLocomotionLogic_State_Sprinting --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Moving : SprintEnded
GameDemo_FirstPersonPlayerLocomotionLogic_State_Sprinting --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Sprinting : DashRequested

GameDemo_FirstPersonPlayerLocomotionLogic_State_Active : OnPhysicsTick → MovementComputed
GameDemo_FirstPersonPlayerLocomotionLogic_State_Active : OnPushed → VelocityChanged
GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching_CrouchingIdle : OnEnter → Idle
GameDemo_FirstPersonPlayerLocomotionLogic_State_Crouching_CrouchingMoving : OnEnter → Move
GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing : OnEnter → VelocityChanged
GameDemo_FirstPersonPlayerLocomotionLogic_State_Dashing : OnPhysicsTick → MovementComputed
GameDemo_FirstPersonPlayerLocomotionLogic_State_Falling : OnEnter → Fall
GameDemo_FirstPersonPlayerLocomotionLogic_State_Grounded : OnJump → VelocityChanged
GameDemo_FirstPersonPlayerLocomotionLogic_State_Idle : OnEnter → Idle
GameDemo_FirstPersonPlayerLocomotionLogic_State_Jumping : OnEnter → Jump
GameDemo_FirstPersonPlayerLocomotionLogic_State_Jumping : OnJump → VelocityChanged
GameDemo_FirstPersonPlayerLocomotionLogic_State_Liftoff : OnEnter → Jump
GameDemo_FirstPersonPlayerLocomotionLogic_State_Moving : OnEnter → Move

[*] --> GameDemo_FirstPersonPlayerLocomotionLogic_State_Idle
@enduml