@startuml

package App-Scene [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.tscn]] {
    class App  {
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs ScriptFile]]
        [Provisions]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:32 IAppRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/app/domain/AppRepo.cs Script]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:33 IMultiplayerRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/domain/IMultiplayerRepo.cs Script]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:34 IMultiplayerLogic]] - [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/state/MultiplayerLogic.cs Script]]
        --
        [Nodes]
        Menu - [[vscode://file/E:/Projects/2025/GameDemo/src/menu/Menu.cs Script]]
        Splash - [[vscode://file/E:/Projects/2025/GameDemo/src/menu/splash/Splash.cs Script]]
        MultiplayerManager - [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs Script]]
        MultiplayerMenu - [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs Script]]
        [Properties]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:52 AnimationPlayer]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:43 AppBinding]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:41 AppLogic]] - [[vscode://file/E:/Projects/2025/GameDemo/src/app/state/AppLogic.cs Script]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:40 AppRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/app/domain/AppRepo.cs Script]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:51 BlankScreen]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:25 Game]] - [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs Script]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:50 GamePreview]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:26 Instantiator]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:49 Menu]] - [[vscode://file/E:/Projects/2025/GameDemo/src/menu/Menu.cs Script]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:54 MultiplayerManager]] - [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs Script]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:55 MultiplayerMenu]] - [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs Script]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:53 Splash]] - [[vscode://file/E:/Projects/2025/GameDemo/src/menu/splash/Splash.cs Script]]
        --
        [Methods]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:77 _Input()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:15 _Notification()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:169 FadeInFromBlack()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:175 FadeToBlack()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:181 HideMenus()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:59 Initialize()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:153 OnAnimationFinished()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:187 OnExitTree()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:151 OnLoadGame()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:149 OnNewGame()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:92 OnReady()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/App.cs:199 OnSaveFileLoaded()]]
    }
    class Menu  {
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/Menu.cs ScriptFile]]
        [Properties]
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/Menu.cs:22 LoadGameButton]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/Menu.cs:20 NewGameButton]]
        --
        [Methods]
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/Menu.cs:17 _Notification()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/Menu.cs:39 OnExitTree()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/Menu.cs:46 OnLoadGamePressed()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/Menu.cs:45 OnNewGamePressed()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/Menu.cs:33 OnReady()]]
    }
    class Splash  {
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/splash/Splash.cs ScriptFile]]
        [Dependencies]
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/splash/Splash.cs:21 AppRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/app/domain/AppRepo.cs Script]]
        --
        [Properties]
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/splash/Splash.cs:16 AnimationPlayer]]
        --
        [Methods]
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/splash/Splash.cs:34 _Input()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/splash/Splash.cs:13 _Notification()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/splash/Splash.cs:31 OnAnimationFinished()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/splash/Splash.cs:28 OnExitTree()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/menu/splash/Splash.cs:25 OnReady()]]
    }
    package MultiplayerManager-Type [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs]] {
        class MultiplayerManager  {
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs ScriptFile]]
            [Provisions]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:20 IMultiplayerRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/domain/IMultiplayerRepo.cs Script]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:21 IMultiplayerLogic]] - [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/state/MultiplayerLogic.cs Script]]
            --
            [Properties]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:29 MultiplayerBinding]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:28 MultiplayerLogic]] - [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/state/MultiplayerLogic.cs Script]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:27 MultiplayerRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/domain/IMultiplayerRepo.cs Script]]
            --
            [Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:16 _Notification()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:103 Disconnect()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:93 HostGame()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:98 JoinGame()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:128 OnConnectedToServer()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:139 OnConnectionFailed()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:176 OnExitTree()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:108 OnPeerConnected()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:122 OnPeerDisconnected()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:47 OnReady()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:145 OnServerDisconnected()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:168 RegisterPeerOnClient()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:151 RegisterPeerOnServer()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/MultiplayerManager.cs:33 Setup()]]
        }
        class MultiplayerLogic  {
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/state/MultiplayerLogic.cs ScriptFile]]
            [Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/state/MultiplayerLogic.cs:12 GetInitialState()]]
        }
        MultiplayerManager::MultiplayerLogic ---> MultiplayerLogic
    }
    class MultiplayerMenu  {
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs ScriptFile]]
        [Dependencies]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:21 MultiplayerRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/domain/IMultiplayerRepo.cs Script]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:24 MultiplayerLogic]] - [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/state/MultiplayerLogic.cs Script]]
        --
        [Properties]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:40 AddressLineEdit]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:52 CloseButton]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:37 DisconnectButton]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:31 HostButton]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:34 JoinButton]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:49 PlayerList]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:43 PortSpinBox]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:46 StatusLabel]]
        --
        [Interface Methods]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:89 HideMenu()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:83 ShowMenu()]]
        [Methods]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:17 _Notification()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:110 OnDisconnectButtonPressed()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:170 OnExitTree()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:94 OnHostButtonPressed()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:116 OnIsOnlineChanged()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:101 OnJoinButtonPressed()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:121 OnPeerConnected()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:126 OnPeerDisconnected()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:61 OnReady()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:74 OnResolved()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:57 Setup()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:160 UpdatePlayerList()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer_menu/MultiplayerMenu.cs:131 UpdateUI()]]
    }
    class AppLogic  {
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/state/AppLogic.cs ScriptFile]]
        [Methods]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/state/AppLogic.cs:12 GetInitialState()]]
    }
    class AppRepo  {
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/domain/AppRepo.cs ScriptFile]]
        [Interface Methods]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/domain/AppRepo.cs:58 OnEnterGame()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/domain/AppRepo.cs:59 OnExitGame()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/domain/AppRepo.cs:56 OnMainMenuEntered()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/domain/AppRepo.cs:54 SkipSplashScreen()]]
        [Methods]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/domain/AppRepo.cs:63 Dispose()]]
        [[vscode://file/E:/Projects/2025/GameDemo/src/app/domain/AppRepo.cs:80 Dispose()]]
    }
    package Game-Scene [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.tscn]] {
        class Game  {
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs ScriptFile]]
            [Dependencies]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:74 AppRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/app/domain/AppRepo.cs Script]]
            [Provisions]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:68 IGameRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs Script]]
            --
            [Nodes]
            PlayerCamera - [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs Script]]
            Player - [[vscode://file/E:/Projects/2025/GameDemo/src/player/FirstPersonPlayer.cs Script]]
            Map - [[vscode://file/E:/Projects/2025/GameDemo/src/map/Map.cs Script]]
            CollectorProxyManager - [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs Script]]
            InGameUi - [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs Script]]
            InGameAudio - [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs Script]]
            DeathMenu - [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs Script]]
            WinMenu - [[vscode://file/E:/Projects/2025/GameDemo/src/win_menu/WinMenu.cs Script]]
            PauseMenu - [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs Script]]
            [Properties]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:60 DeathMenu]] - [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs Script]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:36 EntityTable]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:34 Environment]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:33 FileSystem]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:48 GameBinding]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:39 GameChunk]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:46 GameLogic]] - [[vscode://file/E:/Projects/2025/GameDemo/src/game/state/GameLogic.cs Script]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:45 GameRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs Script]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:59 InGameUi]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:31 JsonOptions]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:58 Map]] - [[vscode://file/E:/Projects/2025/GameDemo/src/map/Map.cs Script]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:62 PauseMenu]] - [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs Script]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:56 Player]] - [[vscode://file/E:/Projects/2025/GameDemo/src/player/IPlayer.cs Script]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:54 PlayerCamera]] - [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/IPlayerCamera.cs Script]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:38 SaveFile]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:35 SaveFilePath]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:61 WinMenu]] - [[vscode://file/E:/Projects/2025/GameDemo/src/win_menu/WinMenu.cs Script]]
            --
            [Interface Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:279 LoadExistingGame()]]
            [Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:235 _Input()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:26 _Notification()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:285 FinishedLoadingSaveFile()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:261 OnDeathMenuTransitioned()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:264 OnExitTree()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:243 OnMainMenu()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:258 OnPauseMenuSaveRequested()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:255 OnPauseMenuTransitioned()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:147 OnResolved()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:246 OnResume()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:249 OnStart()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:252 OnWinMenuTransitioned()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:288 SetPauseMode()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/Game.cs:78 Setup()]]
        }
        package FirstPersonCamera-Scene [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.tscn]] {
            class FirstPersonCamera  {
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs ScriptFile]]
                [Dependencies]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:52 GameRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs Script]]
                --
                [Interface Properties]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:87 CameraBasis]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:83 CameraLocalPosition]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:54 CameraLogic]] - [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/State/FirstPersonCameraLogic.cs Script]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:193 CameraLogic]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:84 GimbalRotationHorizontal]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:85 GimbalRotationVertical]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:62 Offset]]
                [Properties]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:56 CameraBinding]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:77 CameraNode]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:48 FirstPersonCameraChunk]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:71 GimbalHorizontalNode]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:74 GimbalVerticalNode]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:190 OffsetPosition]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:64 Settings]] - [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCameraSettings.cs Script]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:189 SpringArmTargetPosition]]
                --
                [Interface Methods]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:183 UseFirstPersonCamera()]]
                [Methods]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:175 _Input()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:42 _Notification()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:195 OnExitTree()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:150 OnPhysicsProcess()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:128 OnResolved()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:91 Setup()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCamera.cs:186 UsePlayerCamera()]]
            }
            class FirstPersonCameraLogic  {
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/State/FirstPersonCameraLogic.cs ScriptFile]]
                [Properties]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/State/FirstPersonCameraLogic.cs:15 Value]]
                --
                [Methods]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/State/FirstPersonCameraLogic.cs:13 GetInitialState()]]
            }
            class FirstPersonCameraSettings  {
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCameraSettings.cs ScriptFile]]
                [Properties]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCameraSettings.cs:11 JoypadSensitivity]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCameraSettings.cs:8 MouseSensitivity]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCameraSettings.cs:17 VerticalMax]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/player_camera/FirstPersonCameraSettings.cs:23 VerticalMin]]
            }
            FirstPersonCamera::FirstPersonCameraLogic ---> FirstPersonCameraLogic
            FirstPersonCamera::FirstPersonCameraSettings ---> FirstPersonCameraSettings
        }
        class Player << (S,black) >> {
            [[vscode://file/E:/Projects/2025/GameDemo/src/player/Player.tscn SceneFile]]
            [Nodes]
            PlayerModel - [[vscode://file/E:/Projects/2025/GameDemo/src/player/PlayerModel.tscn Script]]
        }
        package Map-Scene [[vscode://file/E:/Projects/2025/GameDemo/src/map/Map.tscn]] {
            class Map  {
                [[vscode://file/E:/Projects/2025/GameDemo/src/map/Map.cs ScriptFile]]
                [Dependencies]
                [[vscode://file/E:/Projects/2025/GameDemo/src/map/Map.cs:43 GameRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs Script]]
                --
                [Nodes]
                DeathPlane - [[vscode://file/E:/Projects/2025/GameDemo/src/death_plane/DeathPlane.cs Script]]
                TreeTrunkSmall2 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/tree_trunk/TreeTrunkSmall.tscn Script]]
                TreeTrunkSmall - [[vscode://file/E:/Projects/2025/GameDemo/src/map/tree_trunk/TreeTrunkSmall.tscn Script]]
                LargeTreeTrunk - [[vscode://file/E:/Projects/2025/GameDemo/src/map/large_tree_trunk/LargeTreeTrunk.tscn Script]]
                Jumpshroom2 - [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom4 - [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom3 - [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom5 - [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom9 - [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom6 - [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom8 - [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom7 - [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Coin - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin26 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin27 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin28 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin29 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin30 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin43 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin44 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin31 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin2 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin32 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin42 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin33 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin19 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin24 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin25 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin20 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin22 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin3 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin4 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin9 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin12 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin15 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin16 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin13 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin14 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin38 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin39 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin41 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin37 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin5 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin6 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin7 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin8 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin10 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin40 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin17 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin11 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin34 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                Coin36 - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs Script]]
                TreeTrunkSmall - [[vscode://file/E:/Projects/2025/GameDemo/src/map/tree_trunk/TreeTrunkSmall.tscn Script]]
                Jumpshroom - [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Fence - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence2 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence3 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence4 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence8 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence12 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence13 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence9 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence10 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence11 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence14 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence15 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence16 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence17 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence5 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence6 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence7 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/fence/Fence.tscn Script]]
                Cloud - [[vscode://file/E:/Projects/2025/GameDemo/src/map/cloud/Cloud.tscn Script]]
                Cloud2 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/cloud/Cloud.tscn Script]]
                Cloud3 - [[vscode://file/E:/Projects/2025/GameDemo/src/map/cloud/Cloud.tscn Script]]
                [Properties]
                [[vscode://file/E:/Projects/2025/GameDemo/src/map/Map.cs:37 Coins]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/map/Map.cs:30 MapChunk]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/map/Map.cs:44 MapLogic]] - [[vscode://file/E:/Projects/2025/GameDemo/src/map/state/MapLogic.cs Script]]
                --
                [Interface Methods]
                [[vscode://file/E:/Projects/2025/GameDemo/src/map/Map.cs:48 GetCoinCount()]]
                [Methods]
                [[vscode://file/E:/Projects/2025/GameDemo/src/map/Map.cs:21 _Notification()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/map/Map.cs:52 OnResolved()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/map/Map.cs:50 Setup()]]
            }
            class DeathPlane  {
                [[vscode://file/E:/Projects/2025/GameDemo/src/death_plane/DeathPlane.cs ScriptFile]]
                [Methods]
                [[vscode://file/E:/Projects/2025/GameDemo/src/death_plane/DeathPlane.cs:10 _Notification()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/death_plane/DeathPlane.cs:16 OnBodyEntered()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/death_plane/DeathPlane.cs:14 OnExitTree()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/death_plane/DeathPlane.cs:12 OnReady()]]
            }
            package Jumpshroom-Scene [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.tscn]] {
                class Jumpshroom  {
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs ScriptFile]]
                    [Dependencies]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs:50 GameRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs Script]]
                    --
                    [Properties]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs:42 AnimationPlayer]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs:43 Area3D]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs:44 CooldownTimer]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs:35 ImpulseStrength]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs:32 JumpshroomBinding]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs:30 JumpshroomLogic]] - [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/state/JumpshroomLogic.cs Script]]
                    --
                    [Methods]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs:19 _Notification()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs:102 OnAnimationFinished()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs:84 OnAreaBodyEntered()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs:82 OnCooldownTimeout()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs:105 OnExitTree()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs:60 OnResolved()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs:94 OnShroomLoaded()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/Jumpshroom.cs:54 Setup()]]
                }
                class JumpshroomLogic  {
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/state/JumpshroomLogic.cs ScriptFile]]
                    [Methods]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/jumpshroom/state/JumpshroomLogic.cs:12 GetInitialState()]]
                }
                Jumpshroom::JumpshroomLogic ---> JumpshroomLogic
            }
            package Coin-Scene [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.tscn]] {
                class Coin  {
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs ScriptFile]]
                    [Dependencies]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:34 GameRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs Script]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:35 MultiplayerRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/domain/IMultiplayerRepo.cs Script]]
                    --
                    [Interface Properties]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:37 CoinLogic]] - [[vscode://file/E:/Projects/2025/GameDemo/src/coin/state/CoinLogic.cs Script]]
                    [Properties]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:21 AnimationPlayer]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:40 CoinBinding]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:22 CoinModel]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:28 CollectionTimeInSeconds]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:48 CollectorDetector]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:38 Settings]]
                    --
                    [Methods]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:17 _Notification()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:145 GetCollectorName()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:113 OnCollectorDetectorBodyEntered()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:220 OnExitTree()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:110 OnPhysicsProcess()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:65 OnReady()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:80 OnResolved()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:166 RequestCollection()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:53 Setup()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:160 StartCollectionLocal()]]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/Coin.cs:193 StartCollectionRemote()]]
                }
                class CoinLogic  {
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/state/CoinLogic.cs ScriptFile]]
                    [Methods]
                    [[vscode://file/E:/Projects/2025/GameDemo/src/coin/state/CoinLogic.cs:12 GetInitialState()]]
                }
                Coin::CoinLogic ---> CoinLogic
            }
            class MapLogic  {
                [[vscode://file/E:/Projects/2025/GameDemo/src/map/state/MapLogic.cs ScriptFile]]
                [Methods]
                [[vscode://file/E:/Projects/2025/GameDemo/src/map/state/MapLogic.cs:12 GetInitialState()]]
            }
            Map::DeathPlane ---> DeathPlane
            Map::Jumpshroom2 ---> Jumpshroom
            Map::Coin ---> Coin
            Map::MapLogic ---> MapLogic
        }
        class PlayerManager  {
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs ScriptFile]]
            [Dependencies]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs:20 MultiplayerRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/multiplayer/domain/IMultiplayerRepo.cs Script]]
            --
            [Properties]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs:27 PauseContainer]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs:33 PlayerScene]]
            --
            [Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs:13 _Notification()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs:154 CreatePlayerForPeer()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs:110 CreateRemotePlayer()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs:137 EnsureLocalPlayerAuthority()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs:130 OnExitTree()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs:70 OnIsOnlineChanged()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs:78 OnPeerConnected()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs:101 OnPeerDisconnected()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs:39 OnReady()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs:46 OnResolved()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/PlayerManager.cs:35 Setup()]]
        }
        class InGameUI  {
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs ScriptFile]]
            [Dependencies]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:21 AppRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/app/domain/AppRepo.cs Script]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:22 GameRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs Script]]
            --
            [Properties]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:29 CoinsLabel]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:38 InGameUIBinding]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:36 InGameUILogic]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:30 StateLabel]]
            --
            [Interface Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:134 SetCoinsLabel()]]
            [Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:17 _Notification()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:67 _Process()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:102 FormatFirstPersonStateName()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:121 FormatStateNameFallback()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:137 OnExitTree()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:47 OnResolved()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:45 Setup()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:75 UpdatePlayerLogic()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_ui/InGameUI.cs:85 UpdateStateLabel()]]
        }
        package InGameAudio-Scene [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.tscn]] {
            class InGameAudio  {
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs ScriptFile]]
                [Dependencies]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:26 AppRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/app/domain/AppRepo.cs Script]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:28 GameRepo]] - [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs Script]]
                --
                [Nodes]
                GameMusic - [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                MainMenuMusic - [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                [Properties]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:16 Bounce]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:15 CoinCollected]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:20 GameMusic]] - [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:36 InGameAudioBinding]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:34 InGameAudioLogic]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:19 MainMenuMusic]] - [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:17 PlayerDied]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:18 PlayerJumped]]
                --
                [Methods]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:11 _Notification()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:71 OnExitTree()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:42 OnResolved()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:40 Setup()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:84 StartGameMusic()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/InGameAudio.cs:77 StartMainMenuMusic()]]
            }
            class DimmableAudioStreamPlayer  {
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs ScriptFile]]
                [Properties]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:23 FadeTween]]
                --
                [Interface Methods]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:33 FadeIn()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:39 FadeOut()]]
                [Methods]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:27 _Ready()]]
                [[vscode://file/E:/Projects/2025/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:45 SetupFade()]]
            }
            InGameAudio::GameMusic ---> DimmableAudioStreamPlayer
        }
        class DeathMenu  {
            [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs ScriptFile]]
            [Properties]
            [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs:38 AnimationPlayer]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs:39 FadeAnimationPlayer]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs:37 MainMenuButton]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs:36 TryAgainButton]]
            --
            [Interface Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs:57 Animate()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs:60 FadeIn()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs:62 FadeOut()]]
            [Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs:23 _Notification()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs:68 OnAnimationFinished()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs:50 OnExitTree()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs:66 OnMainMenuPressed()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs:43 OnReady()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/death_menu/DeathMenu.cs:64 OnTryAgainPressed()]]
        }
        class WinMenu  {
            [[vscode://file/E:/Projects/2025/GameDemo/src/win_menu/WinMenu.cs ScriptFile]]
            [Properties]
            [[vscode://file/E:/Projects/2025/GameDemo/src/win_menu/WinMenu.cs:26 AnimationPlayer]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/win_menu/WinMenu.cs:25 MainMenuButton]]
            --
            [Interface Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/win_menu/WinMenu.cs:46 FadeIn()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/win_menu/WinMenu.cs:51 FadeOut()]]
            [Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/win_menu/WinMenu.cs:21 _Notification()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/win_menu/WinMenu.cs:48 OnAnimationFinished()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/win_menu/WinMenu.cs:42 OnExitTree()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/win_menu/WinMenu.cs:44 OnMainMenuPressed()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/win_menu/WinMenu.cs:40 OnReady()]]
        }
        class PauseMenu  {
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs ScriptFile]]
            [Properties]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:32 AnimationPlayer]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:31 MainMenuButton]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:29 ResumeButton]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:30 SaveButton]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:34 SaveOverlay]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:33 SaveOverlayAnimationPlayer]]
            --
            [Interface Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:74 FadeIn()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:79 FadeOut()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:82 OnSaveCompleted()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:81 OnSaveStarted()]]
            [Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:25 _Notification()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:85 Animate()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:76 OnAnimationFinished()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:62 OnExitTree()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:70 OnMainMenuPressed()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:54 OnReady()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:71 OnResumePressed()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/pause_menu/PauseMenu.cs:72 OnSavePressed()]]
        }
        class GameLogic  {
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/state/GameLogic.cs ScriptFile]]
            [Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/state/GameLogic.cs:12 GetInitialState()]]
        }
        class GameRepo  {
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs ScriptFile]]
            [Interface Properties]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:106 CameraBasis]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:109 GlobalCameraDirection]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:99 IsMouseCaptured]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:101 IsPaused]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:113 NumCoinsAtStart]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:111 NumCoinsCollected]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:103 PlayerGlobalPosition]]
            --
            [Interface Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:167 OnFinishCoinCollection()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:183 OnGameEnded()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:181 OnJump()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:202 OnJumpshroomUsed()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:190 Pause()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:196 Resume()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:157 SetCameraBasis()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:154 SetIsMouseCaptured()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:204 SetNumCoinsAtStart()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:207 SetNumCoinsCollected()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:151 SetPlayerGlobalPosition()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:160 StartCoinCollection()]]
            [Methods]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:212 Dispose()]]
            [[vscode://file/E:/Projects/2025/GameDemo/src/game/domain/GameRepo.cs:239 Dispose()]]
        }
        Game::PlayerCamera ---> FirstPersonCamera
        Game::Player ---> Player
        Game::Map ---> Map
        Game::CollectorProxyManager ---> PlayerManager
        Game::InGameUi ---> InGameUI
        Game::InGameAudio ---> InGameAudio
        Game::DeathMenu ---> DeathMenu
        Game::WinMenu ---> WinMenu
        Game::PauseMenu ---> PauseMenu
        Game::GameLogic ---> GameLogic
        Game::GameRepo ---> GameRepo
    }
    App::Menu ---> Menu
    App::Splash ---> Splash
    App::MultiplayerManager ---> MultiplayerManager
    App::MultiplayerMenu ---> MultiplayerMenu
    App::AppLogic ---> AppLogic
    App::AppRepo ---> AppRepo
    App::Game ---> Game
}

@enduml