@startuml FirstPersonCameraLogic
state "FirstPersonCameraLogic State" as GameDemo_FirstPersonCameraLogic_State {
  state "InputDisabled" as GameDemo_FirstPersonCameraLogic_State_InputDisabled
  state "InputEnabled" as GameDemo_FirstPersonCameraLogic_State_InputEnabled
}

GameDemo_FirstPersonCameraLogic_State --> GameDemo_FirstPersonCameraLogic_State : PhysicsTicked
GameDemo_FirstPersonCameraLogic_State --> GameDemo_FirstPersonCameraLogic_State : TargetPositionChanged
GameDemo_FirstPersonCameraLogic_State_InputDisabled --> GameDemo_FirstPersonCameraLogic_State_InputEnabled : EnableInput
GameDemo_FirstPersonCameraLogic_State_InputEnabled --> GameDemo_FirstPersonCameraLogic_State_InputDisabled : DisableInput
GameDemo_FirstPersonCameraLogic_State_InputEnabled --> GameDemo_FirstPersonCameraLogic_State_InputEnabled : JoyPadInputOccurred
GameDemo_FirstPersonCameraLogic_State_InputEnabled --> GameDemo_FirstPersonCameraLogic_State_InputEnabled : MouseInputOccurred

GameDemo_FirstPersonCameraLogic_State : OnPhysicsTicked → CameraLocalPositionChanged, GimbalRotationChanged, GlobalTransformChanged

[*] --> GameDemo_FirstPersonCameraLogic_State_InputDisabled
@enduml